// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyadipkxvrwunhzjgcfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5YWRpcGt4dnJ3dW5oempnY2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTI2ODMsImV4cCI6MjA3MTY2ODY4M30.yntJHNSIS67HjUkcwMb2ErEiG9HqFUFx-5lLWk-UaDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});